# This is a basic workflow to help you get started with Actions

name: renovate-bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
  - cron: "0 2 * * 1-5"
  issue_comment:
    types: [edited]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g yarn pnpm
      - run: npm install -g renovate
      - env: 
          GIT: ${{secrets.GIT_TOKEN}}
        run: |
          echo $GIT
          export GITHUB_COM_TOKEN=$GIT
          export RENOVATE_CONFIG_FILE='.github/renovate-bot.js'
          export LOG_LEVEL=debug
          export RENOVATE_TOKEN=$GIT
          renovate
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
